name: Sign Out

on:
  schedule:
    # UTC+8 9~17 -> UTC+0 1~9, run every day.
    - cron: "0 9 * * *"
  workflow_dispatch:

jobs:
  run-signout:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Docker Pull
      run: docker pull wulukewu/mcl-sign-in-system:latest

    - name: Docker Sign Out
      run: |      
        username="${{ secrets.username }}"
        password="${{ secrets.password }}"
        otpauth="${{ secrets.otpauth }}"
        
        docker run wulukewu/mcl-sign-in-system:latest\
          --inorout signout \
          --username "$username" \
          --password "$password" \
          --otpauth "$otpauth" \
